
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    url: jdbc:mysql://172.16.1.115:3306/oomall_inner?serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
  redis:
    # Redis服务器地址
    host: 172.16.4.141
    # Redis服务器连接端口
    port: 6379


#  consumer:
#    timeout: 4000
#    check: false