#spring:
#  datasource:
#    url: jdbc:mysql://172.16.1.163:3306/oomall?serverTimezone=GMT%2B8
#    username: dbuser
#    password: 123456
#    druid:
#      stat-view-servlet:
#        login-username: admin
#        login-password: 123456
#        enabled: true
#        url-pattern: /druid/*
#  redis:
#    # Redis服务器地址
#    host: 172.16.1.187
#    # Redis服务器连接端口
#    port: 6379
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 172.16.4.171:8848

spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    url: jdbc:mysql://172.16.1.163:3306/oomall?serverTimezone=GMT%2B8
    username: dbuser
    password: 123456
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
  redis:
    # Redis服务器地址
    host: 172.16.1.187
    # Redis服务器连接端口
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 114.215.198.238:8848